-- ============================================================
-- Remove payment notifications
-- ============================================================
-- Payments remain available in Contribution Logs. They should not
-- occupy the Notifications area, which is reserved for important matters.

BEGIN;

-- Remove notifications already generated by the payment trigger.
DELETE FROM public.notifications
WHERE type = 'payment';

-- Prevent future payment rows from generating notification rows.
DROP TRIGGER IF EXISTS trg_notify_on_payment ON public.payments;
DROP FUNCTION IF EXISTS public.notify_on_payment();

COMMIT;